# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Stable Linter, Build, Unit Test

env:
  FLUTTER_VERSION: "release"
  
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    name: Lint flutter code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        
      # Add formating standards
      - run: |
          cd ./memory_enhancer_app
          flutter pub add --dev effective_dart
          flutter pub get

      # Analyze
      - name: Analyze Flutter
        uses: ValentinVignal/action-dart-analyze@v0.11
        with:
          fail-on: "analyze"

  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: |
          cd ./memory_enhancer_app
          flutter pub get
        
      - name: Build APK
        run: |
          cd ./memory_enhancer_app
          flutter build apk
             
      - name: 'Upload APK Artifact'
        uses: 'actions/upload-artifact@v2'
        with:
          name: memory_enhancer_app-apk-${{env.FLUTTER_VERSION}}
          path: ./memory_enhancer_app/build/app/outputs/flutter-apk/*.apk
            
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
      - run: |
          cd ./memory_enhancer_app
          flutter pub get
      
      - name: Run tests
        run: |
          cd ./memory_enhancer_app
          flutter test
